name: Update Prices

on:
  schedule:
    - cron: "0 */4 * * *"  # Tiap 4 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install requests
        run: pip install requests
      - name: Run updater
        run: python update_prices.py
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update prices" || echo "No changes"
          git push